/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesUiuxRouteImport } from './routes/services.uiux'
import { Route as ServicesMobileRouteImport } from './routes/services.mobile'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'
import { Route as ServicesGraphicsRouteImport } from './routes/services.graphics'
import { Route as ServicesErpRouteImport } from './routes/services.erp'
import { Route as ServicesCrmRouteImport } from './routes/services.crm'
import { Route as ServicesCloudRouteImport } from './routes/services.cloud'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUiuxRoute = ServicesUiuxRouteImport.update({
  id: '/uiux',
  path: '/uiux',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileRoute = ServicesMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGraphicsRoute = ServicesGraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesErpRoute = ServicesErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCrmRoute = ServicesCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudRoute = ServicesCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/graphics': typeof ServicesGraphicsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/graphics': typeof ServicesGraphicsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/graphics': typeof ServicesGraphicsRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/uiux': typeof ServicesUiuxRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/services/cloud'
    | '/services/crm'
    | '/services/erp'
    | '/services/graphics'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/sitemap.xml'
    | '/services/cloud'
    | '/services/crm'
    | '/services/erp'
    | '/services/graphics'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/services/cloud'
    | '/services/crm'
    | '/services/erp'
    | '/services/graphics'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/uiux'
    | '/services/web'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/web': {
      id: '/services/web'
      path: '/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/uiux': {
      id: '/services/uiux'
      path: '/uiux'
      fullPath: '/services/uiux'
      preLoaderRoute: typeof ServicesUiuxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile': {
      id: '/services/mobile'
      path: '/mobile'
      fullPath: '/services/mobile'
      preLoaderRoute: typeof ServicesMobileRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/graphics': {
      id: '/services/graphics'
      path: '/graphics'
      fullPath: '/services/graphics'
      preLoaderRoute: typeof ServicesGraphicsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/erp': {
      id: '/services/erp'
      path: '/erp'
      fullPath: '/services/erp'
      preLoaderRoute: typeof ServicesErpRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/crm': {
      id: '/services/crm'
      path: '/crm'
      fullPath: '/services/crm'
      preLoaderRoute: typeof ServicesCrmRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud': {
      id: '/services/cloud'
      path: '/cloud'
      fullPath: '/services/cloud'
      preLoaderRoute: typeof ServicesCloudRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCloudRoute: typeof ServicesCloudRoute
  ServicesCrmRoute: typeof ServicesCrmRoute
  ServicesErpRoute: typeof ServicesErpRoute
  ServicesGraphicsRoute: typeof ServicesGraphicsRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesMobileRoute: typeof ServicesMobileRoute
  ServicesUiuxRoute: typeof ServicesUiuxRoute
  ServicesWebRoute: typeof ServicesWebRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCloudRoute: ServicesCloudRoute,
  ServicesCrmRoute: ServicesCrmRoute,
  ServicesErpRoute: ServicesErpRoute,
  ServicesGraphicsRoute: ServicesGraphicsRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesMobileRoute: ServicesMobileRoute,
  ServicesUiuxRoute: ServicesUiuxRoute,
  ServicesWebRoute: ServicesWebRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
